[package]
name = "rust-est"
version = "0.1.0"
authors = ["Kirill Marchuk <62mkv@mail.ru>"]
edition = "2018"

[dependencies]
libloading = "0.5"
encoding = "0.2"
clap = { version = "~2.33.0", features = ["yaml"] }
lazy_static = "1.3.0"
array-init = "0.0.4"